name: Continuous Integration

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        working-directory: ${{github.workspace}}
        run: npm install
      
      - name: Build
        working-directory: ${{github.workspace}}
        run: npm run build

      - name: Deploy
        working-directory: ${{github.workspace}}
        run: gh-pages -b master -d build